routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('admin.index'));
});

Auth::routes(['verify' => true]);

Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware(['web' , 'auth'])
    ->group(function(){

        Route::get('/', 'DashboardController@index')->name('index');

        Route::name('link.')
        ->prefix('source')
        ->group(function(){
            Route::get('/', 'LinkController@index')->name('index');
            Route::get('create', 'LinkController@create')->name('create');
            Route::post('store', 'LinkController@store')->name('store');
            Route::get('/edit/{id}', 'LinkController@edit')->name('edit');
            Route::get('/delete/{id}', 'LinkController@destroy')->name('delete');
            Route::post('/update', 'LinkController@update')->name('update');
        });

        Route::name('user.')
        ->prefix('user')
        ->middleware('role:super-admin')
        ->group(function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('/create', 'UserController@store')->name('store');
            Route::post('/update', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@destroy')->name('delete');
        });

        Route::name('postback.')
        ->prefix('postback')
        ->group(function(){
            Route::get('/', 'PostbackController@index')->name('index');
            Route::get('/create/{source}', 'PostbackController@create')->name('create');
            Route::post('/create', 'PostbackController@store')->name('store');

        });

        Route::name('statistic.')
        ->prefix('statistic')
        ->group(function(){
            Route::get('/', 'StatisticController@index')->name('index');
        });

    });

resources/views/admin/index.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <h1>Dashboard</h1>
    </div>
</div>
@endsection

resources/views/admin/links.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
                <h1>Sources</h1>
                <a name="" id="" class="btn btn-outline-primary mb-3 float-right" href="{{ route('admin.link.create') }}" role="button">Create source</a>
                <div class="table-responsive">
                        <table class="table table-striped table-hover">
                                <thead class="thead-inverse">
                                    <tr>
                                        <th>#</th>
                                        @role('super-admin')
                                            <th>User</th>
                                            <th>Campaign 1x</th>
                                        @endrole
                                        <th>Source</th>
                                        <th>Campaign</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {{-- {{ dd($links) }} --}}
                                    @foreach ($links as $link)
                                        <tr>
                                            <td scope="row">{{ $link->id }}</td>
                                            @role('super-admin')
                                                <td>{{ $link->user->name }}</td>
                                                <td>{{ $link->campaign_1x }}</td>
                                            @endrole
                                            <td>{{ $link->source }}</td>
                                            <td>{{ $link->campaign }}</td>
                                            <td>{{ $link->is_active ? 'Active' : 'Non active' }}</td>
                                            <td>
                                                <a class="btn btn-outline-primary" href="{{ route('admin.link.edit', $link->id) }}" role="button">Update</a>
                                                <a class="btn btn-outline-danger" href=" {{ route('admin.link.delete', $link->id) }}" role="button">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                        </table>
                    </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/links_create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Create source</h1>
                <form action="{{ route('admin.link.store') }}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label for="source" class="col-sm-2 col-form-label">Source</label>
                        <div class="col-sm-10">
                        <input type="text" class="form-control" id="source" name="source" placeholder="Source" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="campaign" class="col-sm-2 col-form-label">Campaign</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="campaign" placeholder="Campaign" name="campaign" >
                        </div>
                    </div>
                    @role('super-admin')
                        <fieldset class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">User</legend>
                            <div class="col-sm-10">
                                @foreach ($users as $user)
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="user_id" value="{{ $user->id}}">
                                        <label class="form-check-label" for="gridRadios1">
                                            {{ $user->name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <div class="row">
                                    <label for="campaign_1x" class="col-sm-2 col-form-label">Campaign_1x</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="campaign_1x" placeholder="Campaign_1x" name="campaign_1x" >
                                    </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                    <label for="url" class="col-sm-2 col-form-label">Url</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="url" placeholder="Url" name="url" >
                                    </div>
                            </div>
                        </div>
                    @else
                        <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                    @endrole
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{{ route('admin.link.index') }}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/links_edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Edit source</h1>
                <form action="{{ route('admin.link.update') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id" value="{{ $link->id }}">
                    <fieldset class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">User</legend>
                            <div class="col-sm-10">
                                @foreach ($users as $user)
                                    <div class="form-check">
                                        <input class="form-check-input" type="radio" name="user_id" value="{{ $user->id }}" {{ $user->id === $link->user->id ? 'checked' : '' }}>
                                        <label class="form-check-label" for="user_id">
                                            {{ $user->name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            </div>
                        </fieldset>
                    <div class="form-group row">
                        <label for="source" class="col-sm-2 col-form-label">Source</label>
                        <div class="col-sm-10">
                        <input type="name" class="form-control" id="source" name="source" placeholder="Source" value="{{ $link->source }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="campaign" class="col-sm-2 col-form-label">Campaign</label>
                        <div class="col-sm-10">
                        <input type="name" class="form-control" id="campaign" name="campaign" placeholder="Campaign" value="{{ $link->campaign }}">
                        </div>
                    </div>
                    @role('super-admin')
                    <div class="form-group row">
                            <label for="source_1x" class="col-sm-2 col-form-label">Source 1x</label>
                            <div class="col-sm-10">
                            <input type="name" class="form-control" id="source_1x" name="source_1x" placeholder="Source 1x" value="{{ $link->source_1x }}">
                            </div>
                        </div>
                    <div class="form-group row">
                            <label for="campaign_1x" class="col-sm-2 col-form-label">Campaign 1x</label>
                            <div class="col-sm-10">
                            <input type="name" class="form-control" id="campaign_1x" name="campaign_1x" placeholder="Campaign 1x" value="{{ $link->campaign_1x }}">
                            </div>
                        </div>
                    <div class="form-group row">
                        <label for="url" class="col-sm-2 col-form-label">Url</label>
                        <div class="col-sm-10">
                                <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon3">{{ $domain }}</span>
                                </div>
                                <input type="text" class="form-control" id="url" name="url" placeholder="Url" value="{{ $link->url }}">
                                </div>
                        </div>
                    </div>
                    <fieldset class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">Active</legend>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_active" value="1" {{ $user->is_active == true ? 'checked' : '' }}>
                                    <label class="form-check-label" for="gridRadios1">
                                        Active
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_active" value="0" {{ $user->is_active == false ? 'checked' : '' }}>
                                    <label class="form-check-label" for="gridRadios1">
                                        Non active
                                    </label>
                                </div>
                            </div>
                            </div>
                        </fieldset>
                    @endrole
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{{ route('admin.link.index') }}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
                <h2 class="mt-5">Postback</h2>
                <a name="" id="" class="btn btn-outline-primary mb-3 float-right" href="{{ route('admin.postback.create', $link->id) }}" role="button">Create postback</a>
                <table class="table table-striped table-hover">
                        <thead class="thead-inverse">
                            <tr>
                                <th>#</th>
                                <th>Conversion Type</th>
                                <th>Url</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($postbacks as $postback)
                                <tr>
                                    <td scope="row">{{ $postback->id }}</td>
                                    <td>{{ $postback->event->name }}</td>
                                    <td>{{ $postback->url }}</td>
                                    <td>{{ $postback->is_active ? 'Active' : 'Non active' }}</td>
                                    {{-- <td>
                                        <a class="btn btn-outline-primary" href="{{ route('admin.link.edit', $link->id) }}" role="button">Update</a>
                                        <a class="btn btn-outline-danger" href=" {{ route('admin.link.delete', $link->id) }}" role="button">Delete</a>
                                    </td> --}}
                                </tr>
                            @endforeach
                        </tbody>
                </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/postbacks_create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Edit user</h1>
                <form action="{{ route('admin.postback.store') }}" method="POST">
                    @csrf
                    {{-- {{ dd($link) }} --}}
                    <input type="hidden" name="link_id" value="{{ $link->id }}">
                    <div class="form-group row">
                        <label for="source" class="col-sm-2 col-form-label">Source name</label>
                        <div class="col-sm-10">
                        <input type="source" class="form-control" id="source" name="source" value="{{ $link->source }}" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="campaign" class="col-sm-2 col-form-label">Source campaign</label>
                        <div class="col-sm-10">
                        <input type="source" class="form-control" id="campaign" name="campaign" value="{{ $link->campaign }}" readonly>
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                        <legend class="col-form-label col-sm-2 pt-0">Conversion event</legend>
                        <div class="col-sm-10">
                            @foreach ($events as $event)
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" id="event_{{ $event->id }}" name="event_id" value="{{ $event->id }}">
                                    <label class="form-check-label" for="event_{{ $event->id }}">
                                        {{ $event->name }}
                                    </label>
                                </div>
                            @endforeach
                        </div>
                        </div>
                    </fieldset>
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Postback url</label>
                        <div class="col-sm-10">
                        <input type="url" class="form-control" id="url" placeholder="Postback url" name="url" >
                        <small id="passwordHelpInline" class="text-muted">
                            Click id заключать в {click_id}. Например https://postback.net/convertion?click_id={click_id}
                        </small>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{{ route('admin.link.index') }}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/statistics.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h1>Statistics</h1>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                        <thead class="thead-inverse">
                            <tr>
                                <th>SubID</th>
                                <th>Clicks</th>
                                <th>Regs</th>
                                <th>Dep</th>
                                <th>Curr</th>
                                <th>Prof</th>
                                <th>Comm</th>
                                <th>CountRegDep</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($statistics as $item)
                                <tr>
                                    <td>{{ $item->SubID }}</td>
                                    <td>{{ $item->DirectLink }}</td>
                                    <td>{{ $item->Regs }}</td>
                                    <td>{{ $item->SumDep }}</td>
                                    <td>{{ $item->currency }}</td>
                                    <td class="{{ $item->SumProf > 0 ? 'bg-success text-white' : 'bg-danger text-white' }}">{{ $item->SumProf }}</td>
                                    <td>{{ $item->ItogComission }}</td>
                                    <td>{{ $item->CountRegDep }}</td>
                                    <td>{{ $item->updated_at }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="mx-auto">
            {{ $statistics->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/users.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Users</h1>
                <a name="" id="" class="btn btn-outline-primary mb-3 float-right" href="{{ route('admin.user.create') }}" role="button">Create user</a>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                            <thead class="thead-inverse">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td scope="row">{{ $user->id }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->roles[0]->name }}</td>
                                        <td>
                                            <a class="btn btn-outline-primary" href="{{ route('admin.user.edit', $user->id) }}" role="button">Update</a>
                                            <a class="btn btn-outline-danger" href=" {{ route('admin.user.delete', $user->id) }}" role="button">Delete</a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                    </table>
                </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users_create.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Edit user</h1>
                <form action="{{ route('admin.user.store') }}" method="POST">
                    @csrf
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Campaign name</label>
                        <div class="col-sm-10">
                        <input type="name" class="form-control" id="name" name="name" placeholder="Campaign name" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                        <input type="email" class="form-control" id="email" placeholder="Email" name="email" >
                        </div>
                    </div>
                    <div class="form-group row">
                            <label for="inputEmail3" class="col-sm-2 col-form-label">Password</label>
                            <div class="col-sm-10">
                            <input type="password" class="form-control" id="password" placeholder="Password" name="password" >
                            </div>
                        </div>
                    <fieldset class="form-group">
                        <div class="row">
                        <legend class="col-form-label col-sm-2 pt-0">Role</legend>
                        <div class="col-sm-10">
                            @foreach ($roles as $role)
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="role_id" value="{{ $role->id}}">
                                    <label class="form-check-label" for="gridRadios1">
                                        {{ $role->name }}
                                    </label>
                                    </div>
                            @endforeach
                        </div>
                        </div>
                    </fieldset>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{{ route('admin.user.index') }}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users_edit.blade.php
@extends('admin.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
                <h1>Edit user</h1>
                <form action="{{ route('admin.user.update') }}" method="POST">
                    @csrf
                    <input type="hidden" name="id" value="{{ $user->id }}">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Campaign name</label>
                        <div class="col-sm-10">
                        <input type="name" class="form-control" id="inputEmail3" name="name" placeholder="Campaign name" value="{{ $user->name }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                        <input type="email" class="form-control" id="inputEmail3" placeholder="Email" name="email" value="{{ $user->email }}">
                        </div>
                    </div>
                    <fieldset class="form-group">
                        <div class="row">
                        <legend class="col-form-label col-sm-2 pt-0">Role</legend>
                        <div class="col-sm-10">
                            @foreach ($roles as $role)
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="role_id" value="{{ $role->id}}" {{ $role->id === $user->roles[0]->id ? 'checked' : '' }}>
                                    <label class="form-check-label" for="gridRadios1">
                                        {{ $role->name }}
                                    </label>
                                    </div>
                            @endforeach
                        </div>
                        </div>
                    </fieldset>
                    <fieldset class="form-group">
                            <div class="row">
                            <legend class="col-form-label col-sm-2 pt-0">Deleted</legend>
                            <div class="col-sm-10">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_deleted" value="0" {{ $user->is_deleted === false ? 'checked' : '' }}>
                                    <label class="form-check-label" for="gridRadios1">
                                        Active
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_deleted" value="1" {{ $user->is_deleted === true ? 'checked' : '' }}>
                                    <label class="form-check-label" for="gridRadios1">
                                        Deleted
                                    </label>
                                </div>
                            </div>
                            </div>
                        </fieldset>
                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="{{ route('admin.user.index') }}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </div>
                </form>
        </div>
    </div>
</div>
@endsection