routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('admin.index'));
});

Auth::routes(['verify' => true]);

Route::prefix('admin')
    ->name('admin.')
    ->namespace('Admin')
    ->middleware(['web' , 'auth'])
    ->group(function(){

        Route::get('/', 'DashboardController@index')->name('index');

        Route::name('link.')
        ->prefix('source')
        ->group(function(){
            Route::get('/', 'LinkController@index')->name('index');
            Route::get('create', 'LinkController@create')->name('create');
            Route::post('store', 'LinkController@store')->name('store');
            Route::get('/edit/{id}', 'LinkController@edit')->name('edit');
            Route::get('/delete/{id}', 'LinkController@destroy')->name('delete');
            Route::post('/update', 'LinkController@update')->name('update');
        });

        Route::name('user.')
        ->prefix('user')
        ->middleware('role:super-admin')
        ->group(function(){
            Route::get('/', 'UserController@index')->name('index');
            Route::get('/edit/{id}', 'UserController@edit')->name('edit');
            Route::get('/create', 'UserController@create')->name('create');
            Route::post('/create', 'UserController@store')->name('store');
            Route::post('/update', 'UserController@update')->name('update');
            Route::get('/delete/{id}', 'UserController@destroy')->name('delete');
        });

        Route::name('postback.')
        ->prefix('postback')
        ->group(function(){
            Route::get('/', 'PostbackController@index')->name('index');
            Route::get('/create/{source}', 'PostbackController@create')->name('create');
            Route::post('/create', 'PostbackController@store')->name('store');

        });

        Route::name('statistic.')
        ->prefix('statistic')
        ->group(function(){
            Route::get('/', 'StatisticController@index')->name('index');
        });

    });

resources/views/admin/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @role('super-admin')
                            <a class="nav-link {{ Request::url() == route('admin.user.index') ? 'active' : '' }}" href="{{route('admin.user.index')}}">Users</a>

                        @endrole
                        <a class="nav-link {{ Request::url() == route('admin.link.index') ? 'active' : '' }}" href="{{route('admin.link.index')}}">Sources</a>
                        <a class="nav-link {{ Request::url() == route('admin.statistic.index') ? 'active' : '' }}" href="{{route('admin.statistic.index')}}">Statistics</a>
                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
</body>
</html>